version: '3.4'

services:
  http-nats-proxy:
    image: wshaddix/http-nats-proxy
    depends_on:
      - nats
    ports:
      - "5000:5000"
    environment:
      - HTTP_NATS_PROXY_HOST_PORT=5000
      - HTTP_NATS_PROXY_NAT_URL=nats://nats:4222
      - HTTP_NATS_PROXY_WAIT_TIMEOUT_SECONDS=10
      - HTTP_NATS_PROXY_METRICS_SUBJECT=post.metrics
      - HTTP_NATS_PROXY_LOGS_SUBJECT=post.logs
      - HTTP_NATS_PROXY_TRACE_HEADER=x-trace-id
  nats:
    image: nats:1.0.4
    ports:
      - "8222:8222"
      - "4222:4222"